### PR TITLE
Add LSP Group to Scheme to avoid color errors + Updated README.md to include example lazy.nvim as package manager

### PR DESCRIPTION
**Pull request by dedguy21**
Fix an issue with color where semantic highlighting in nvim 0.9 new lsp group was causing an issue. Also I thought it would be useful to include lazy.nvim plugin manager as well. It is quickly become the new defacto for nvim.

### CODE REVIEW

**Comment by dedguy21** [comment]
Please review, again just adding lsp group to the color scheme so the new lsp semantic highlights don't discolor the settings.

**Comment by dedguy21** [comment]
more testing needed, will reopen later.

**Comment by dedguy21** [comment]
It ready for review, a couple of links in LSP group don't link back to a Treesitter group because you don't seem to use them in the color scheme. But it isn't causing issues that  i have tested

**Comment by MrFixThis** [comment]
Hey @dedguy21 thanks for the PR. I've been testing your changes with several languages to look for any possible problem and I found that, mentioning a case, some elements' highlights from Rust like traits, unions and enums now lack of a proper syntax highlight.

Please consider testing in an exhaustive manner the changes you made and then send to us the corrections. Thank you!

**Comment by dedguy21** [comment]
Edit:

I may have found one: Code Snippet Library
---------------------------
@MrFixThis 

Apologies, I'm only a data analyst. So I can test python and some scripting languages and such. But rust, c, c++, etc are beyond my knowledge. 

Does there exist a code snippet bank for syntax highlight testing these different languages?

**Comment by dedguy21** [comment]
@MrFixThis 
I'm wondering if you cleared your nvim cache from ~/.local and ~/.cache (on Linux), because I'm not having any highlighting issues you pointed out.

**Comment by dedguy21** [comment]
more extensive testing needed

**Pull request closed without merging**
